### ISSUE TITLE
Add body validation

### ISSUE THREAD

**Issue by ajdelgados** [hngi/sentry-my-customer-api#113]
**Describe the bug**
Add body validation for store, notification, transaction and complaint

**Expected behavior**
Response errors when a body doesn't have the correct format

**How do you intend to solve this bug?**
Added express-validation

**Slack username**
@ajdelgados

**Comment by chinazaaa** [comment]
Approved @chinazaaa

**Comment by iAmServer** [comment]
I will take this

**Comment by Tolufolorunso** [comment]
I will deliver this

**Comment by chinazaaa** [comment]
has this being solved? who is working on it?

**Comment by Tolufolorunso** [comment]
@chinazaaa hope I can work on this?

**Comment by chinazaaa** [comment]
Ask @ajdelgados he is the one working on it

**Comment by austitech** [comment]
Update the label of this issue so we know it has been taken. thanks
