### ISSUE TITLE
Create transaction route not working

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-api#115]
**Describe the bug**
The endpoint /transaction/new isn't working. It returns `..._id undefined`

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. After creating a customer account at /customer/new and store at /store/new
2. Post to `/transaction/new` with all necessary cred.

**Expected behavior**
Supposed to return a success message in json format

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu linux]
 - Browser Chrome
 - Version 18.04, 80+

**How do you intend to solve this bug?**
The problem is that async/await wasn't used to get the store, user, customer objects from mongo. And `user_ref_id[0]._id` was referenced when using `Model.findOne` instead of `user_ref_id._id`. So I'll fix it using async/await and fix the vars

**Slack username**
@judgegodwins

**Additional context**

**Comment by kenny-67** [comment]
How did you test it (what parameters did you provide)

**Comment by judgegodwins** [comment]
> How did you test it (what parameters did you provide)

Ok first u'll create a store and a customer account.
Then post to /transaction/new with

**Comment by kenny-67** [comment]
@chinazaaa is this approved?

**Comment by kenny-67** [comment]
I would like to work on this

**Comment by chinazaaa** [comment]
Approved

**Comment by judgegodwins** [comment]
I'm already working on it
