### ISSUE TITLE
Endpoint user/new always returns error of an already existing user with same details

### ISSUE THREAD

**Issue by mhizterkeyz** [hngi/sentry-my-customer-api#127]
**Describe the bug**
The endpoint will always give an error of a user with the same details you have provided existing.

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. POST /user/new with appropriate data
2. See error

**Expected behavior**
It's supposed to create a new user and return that data when you POST to it

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Fixing the issue in the controller.

**Slack username**
@script

**Additional context**

**Comment by iAmServer** [comment]
@chinazaaa assign

**Comment by buka4rill** [comment]
Show a screen shot, I worked on this route yesterday, and it's works fine

**Comment by buka4rill** [comment]
Did you make a pull request for recent updates?

**Comment by chinazaaa** [comment]
send the screenshot of this issue

**Comment by chinazaaa** [comment]
waiting....

or i can close it?

**Comment by mhizterkeyz** [comment]
Yes, you can close it, it works fine now
