### ISSUE TITLE
user/all endpoint does not have authentication

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#132]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
Should have authentication 

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@Naza

**Additional context**

**Comment by buka4rill** [comment]
Assign this to me @chinazaaa

**Comment by chinazaaa** [comment]
oh

**Comment by buka4rill** [comment]
ignore...assign to someone else 🚶‍♂️

**Comment by emmaakachukwu** [comment]
i'll take this if it's available @chinazaaa
