### ISSUE TITLE
Add Products to Store

### ISSUE THREAD

**Issue by sukiejosh** [hngi/sentry-my-customer-api#135]
**What Functionality / Service / Endpoint would you like to add?**
Add/Update goods a store has

**Describe this Functionality / Service / Endpoint**
The User can add goods to an existing store or when creating a store, goods might be updated after every tranasction

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
Add goods to **Store** schema, and update the routes and controllers accordingly 

**Slack username**
@sukiejosh

**Additional context**

**Comment by sukiejosh** [comment]
I would like to work on this

**Comment by chinazaaa** [comment]
hold on

**Comment by Megxos** [comment]
Did you see any product schema?

**Comment by sukiejosh** [comment]
> Did you see any product schema?



> Did you see any product schema?

Nope...Am talking if the Store model

**Comment by Megxos** [comment]
We are not selling products on the App
