### ISSUE TITLE
Implement login with Google

### ISSUE THREAD

**Issue by Megxos** [hngi/sentry-my-customer-api#136]
**What Functionality / Service / Endpoint would you like to add?**
Login with Google

**Describe this Functionality / Service / Endpoint**
Allow user to register/sign in using their Google account.

**Duplicate prevention**
Yes

**Describe how to intend to go about adding this feature**
Use Passportjs Google authentication.

**Slack username**
@Mikah

**Additional context**
Not available

**Comment by chinazaaa** [comment]
are you doing it?

**Comment by Megxos** [comment]
No

**Comment by jobafash** [comment]
@hngibot claim

**Comment by Aptcoder** [comment]
can I take this

**Comment by jobafash** [comment]
@hngibot claim

**Comment by buka4rill** [comment]
Who owns this task??

**Comment by buka4rill** [comment]
This has been done by @Alao-Abiodun

**Comment by Alao-Abiodun** [comment]
https://github.com/hngi/sentry-my-customer-api/issues/136
