### ISSUE TITLE
Restructure database to accept users who registered with Google

### ISSUE THREAD

**Issue by Megxos** [hngi/sentry-my-customer-api#137]
**What Functionality / Service / Endpoint would you like to add?**
Save Google account credentials

**Describe this Functionality / Service / Endpoint**
Add user schema for those who registered using their Google account.

**Duplicate prevention**
No duplicate

**Describe how to intend to go about adding this feature**
Add a Google object in the users schema.

**Slack username**
@Mikah

**Additional context**
No addition

**Comment by sukiejosh** [comment]
Are u doing this....can i do it
