### ISSUE TITLE
Password reset API

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#140]
**What Functionality / Service / Endpoint would you like to add?**
A short statement

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 

**Slack username**
@sandy

**Additional context**

**Comment by sandygudie** [comment]
Dear nerdyphil, it's assigned already thks

**Comment by buka4rill** [comment]
Drop the link to the PR here @sandygudie

**Comment by sandygudie** [comment]
[forget](https://res.cloudinary.com/dvpoiwd0t/image/upload/v1593335257/forget_password_done_fnsgsn.jpg)
[resetpassword](https://res.cloudinary.com/dvpoiwd0t/image/upload/v1593335258/resetsuccessful_czhrdr.jpg)

**Comment by sandygudie** [comment]
**Feature Added**
Password Recovery API

**Description**
Added Password recovery API. The forget password endpoint sends a reset link to the user's email and generates a password  token. 
The reset password endpoint uses the password token (req.query) and new password( req.body) to reset user password . New password generated is encrypted and stored in database.

 **Endpoint testing pics**
[forget_password](https://res.cloudinary.com/dvpoiwd0t/image/upload/v1593433552/forget_password_done_sudgbg.jpg)
[reset_password](https://res.cloudinary.com/dvpoiwd0t/image/upload/v1593433551/resetsuccessful_ecryjx.jpg)

**PR link**
https://github.com/hngi/sentry-my-customer-api/pull/188

**Ticket NO**
140

**Comment by sandygudie** [comment]
PR link
https://github.com/hngi/sentry-my-customer-api/pull/261

**Comment by sandygudie** [comment]
Feature Added
Password Recovery API


PR link
https://github.com/hngi/sentry-my-customer-api/pull/261

Ticket NO
140

Steps to test
-Add a valid email to FROM_EMAIL in the .env file.
-In passwordreset controller file for both endpoints, add valid email to host and user , add email password to password .

testing endpoints
/forgetpassword - req.body(email)
(you should get an email for reset link)
/resetpassword - req.body(new password), req.query(password token)
(you should get a confirmation email)
