### ISSUE TITLE
Create new debt route is broken

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-api#149]
**Describe the bug**
Route to create a debt at `debt/new` is broken

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Post to `/debt/new/` with body params: 
`{
  transaction_id: 'id of already created transaction',
  message,
  status,
  pay_date,
}`

**Expected behavior**
It is supposed to respond with json `{ error: false, message: 'Debt Reminder was created.'}`

**Screenshots**
![Screenshot from 2020-06-27 20-21-10](https://user-images.githubusercontent.com/38760034/85930375-cf9c3880-b8b3-11ea-9323-782780d26ca1.png)

![Screenshot from 2020-06-27 20-37-19](https://user-images.githubusercontent.com/38760034/85930658-1e4ad200-b8b6-11ea-8cb0-bab5d717ef8d.png)

This is what it returns

**Desktop (please complete the following information):**
 - OS: [Ubuntu Linux]
 - Browser [Chrome]
 - Version [18.04, 80+]

**How do you intend to solve this bug?**
The problem is that the route looks for the parameters from `req.params` instead of `req.body`. So I'll change that.
And I also plan to fix the routes `/debt/new/:transaction_id` and `/debt/new/`. The first would get the `transaction_id` from the params and the later from `req.body`. Both routes will point to the `debt_controller`. And I'll also make additions to `app.js` because the debt routes are not connected.

**Slack username**
@judgegodwins

**Additional context**

**Comment by judgegodwins** [comment]
I'll like to work on the issue

**Comment by chinazaaa** [comment]
Approved
