### ISSUE TITLE
Secure email reminder

### ISSUE THREAD

**Issue by olawalejuwonm** [hngi/sentry-my-customer-api#160]
**What Functionality / Service / Endpoint would you like to add?**
Adding the functionality of sending email by using registered email available 

**Describe this Functionality / Service / Endpoint**
This will work on /reminder/email endpoint

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
I will authorize the user and use their details from the request header to send secure emsil
**Slack username**
Please include your slack username here
@OlawaleJuwonM

**Additional context**
![Screenshot_20200628-000821](https://user-images.githubusercontent.com/52759812/85933903-0eda8180-b8d4-11ea-9b65-87144b5446f4.png)

**Comment by emasontech** [comment]
Duplicate of my task. I just fixed it
