### ISSUE TITLE
Getting individual transaction route not working

### ISSUE THREAD

**Issue by kenny-67** [hngi/sentry-my-customer-api#163]
**Describe the bug**
Individual transaction cannot be retrieved by ID

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Go to '/transaction/:transaction id' route

**Expected behavior**
return the individual transaction

**Desktop (please complete the following information):**
 - OS: [e.g. Windows10]
 - Browser [Chrome]

*

**Screenshots**
![transaction-get](https://user-images.githubusercontent.com/41513164/85945946-f486bf00-b938-11ea-826a-2f0c91497a02.PNG)
*How do you intend to solve this bug?**
By fixing the /transaction/:id route

**Slack username**
@kenneth_real

**Additional context**

**Comment by kenny-67** [comment]
I would take this if approved

**Comment by chinazaaa** [comment]
Approved

**Comment by kenny-67** [comment]
On it
