### ISSUE TITLE
Debt route `/debt/all` Should not return all debt Objects in DB

### ISSUE THREAD

**Issue by judgegodwins** [hngi/sentry-my-customer-api#164]
**Describe the bug**
The route `/debt/all` calls `debt.getAll` which returns all debt in DB

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Try creating two user accounts and add debts for all
2. Make a GET request to `/debt/all`

**Expected behavior**
The request is only supposed to return debts pertaining to the user making the request and not all debts in the DB including those of other users.

**Screenshots**
![Screenshot from 2020-06-28 12-54-58](https://user-images.githubusercontent.com/38760034/85946764-9e1c7f00-b93e-11ea-908d-b8784b270461.png)
It just returns everything from the DB

**Desktop (please complete the following information):**
 - OS: [Ubuntu Linux]
 - Browser [chrome]
 - Version [80+]

**How do you intend to solve this bug?**
I intend to add a users email or phone number to the debt schema, so when a user makes a request for all his debt the email or phone number would be passed. This would return all debts pertaining to that store owner 

**Slack username**
@judgegodwins 

**Additional context**

**Comment by judgegodwins** [comment]
I'll like to work on it

**Comment by chinazaaa** [comment]
Approved

**Comment by chinazaaa** [comment]
Redo and make pr

Make sure you pull the recent ones
