### ISSUE TITLE
customer/all returns everyone's customers with my token

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#175]
**Describe the bug**
customer/all returns all the customers with my token

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
It should only return my own customer and not everyone's customers

**Screenshots**
![image](https://user-images.githubusercontent.com/50022245/85960662-2893cb80-b99d-11ea-8d9b-f60918e1df02.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@Naza

**Additional context**

**Comment by buka4rill** [comment]
Whose on this ticket?
