### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by kenny-67** [hngi/sentry-my-customer-api#186]
**Describe the bug**
As the codebase stands now every user token is stored in the data base this raises some issues
1) any user that makes a request to /user/all would be able to see every users token and with this token he can gain access to an account that's not his
2)since the token is only valid for an hour the entry in the database becomes redundant and takes up valuable storage space

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. Go to '/user/all'
2. you would receive an array of data together with the associated token

![api-token](https://user-images.githubusercontent.com/41513164/86001879-747b5a80-ba07-11ea-9d64-2dec612c2b93.PNG)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
1) deleting the api_token entry from the database model
2)modifying the /register/user route to prevent it from sending the token to the database
3) re-route the response to receive its token from the jwt.signmethod

**Slack username**
@kenneth_real

**Additional context**

**Comment by Megxos** [comment]
What if the user forgets his token and want's to view it?

**Comment by kenny-67** [comment]
Then he can login to generate a new token

**Comment by kenny-67** [comment]
tokens are not meant to be stored in a permanent store

**Comment by kenny-67** [comment]
@megxos ...awaiting approval

**Comment by buka4rill** [comment]
I just checked this route out. It doesn't save or return user token whatsoever. Pull updates and test again @kenny-67

**Comment by kenny-67** [comment]
@buka4rill  it still does
Register a new user with all the required fields leaving none out and then send a get request you would see the api_token returned to you

**Comment by Megxos** [comment]
So you want the user to be copying and storing his token elsewhere so as not to forget?
Also, you want the user to generate a new token anytime he forgets the old one...

**Comment by kenny-67** [comment]
@Megxos what exactly are you talking about, the user doesn't need to do anything its all handled by the front end. 
Upon successful registration the token is collected and stored in the browsers local storage, you talk as if its postman the user would use to make request

**Comment by kenny-67** [comment]
Take any app that has login and signup page do you see your token? Its all handled behind the scenes
