### ISSUE TITLE
Change user is_active state on successful verification

### ISSUE THREAD

**Issue by Megxos** [hngi/sentry-my-customer-api#189]
**What Functionality / Service / Endpoint would you like to add?**
Change user is_active state on successful verification

**Describe this Functionality / Service / Endpoint**
is_active state of the user is meant to be true after successfully  verifying their phone number

**Duplicate prevention**
No duplicate

**Describe how to intend to go about adding this feature**
On successful verification, the is_active state will be updated to true and the OTP saved.

**Slack username**
@Mikah

**Comment by EmmanuelAbajo** [comment]
I would like to work on this.

Slack username
@Emmanuel.Abajo

**Comment by emasontech** [comment]
me too i will like to work on this

**Comment by kenny-67** [comment]
Is this assigned to anyone yet or is it open for all

**Comment by EmmanuelAbajo** [comment]
I already met @chinazaaa to assign it to me @kenny-67
