### ISSUE TITLE
Update complaint and transaction API responce to follow the guideline

### ISSUE THREAD

**Issue by Hack-Light** [hngi/sentry-my-customer-api#192]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**
Here is what am seeing
![github1](https://user-images.githubusercontent.com/52836079/86023665-dc3f9e80-ba23-11ea-8957-afd0e2f15ebb.PNG)

Here is what the guidelines says
![Screenshot_20200628-153811](https://user-images.githubusercontent.com/52836079/86023823-17da6880-ba24-11ea-9328-c4defba990bd.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
 I intend to fix it by rewriting the response to follow the laid down guideline for API response

**Slack username**
@Light

**Additional context**

**Comment by iAmServer** [comment]
It as been updated

**Comment by Hack-Light** [comment]
I just uploaded some screenshots

**Comment by iAmServer** [comment]
My PR as not been merged

**Comment by Hack-Light** [comment]
Okay
