### ISSUE TITLE
/user/all returns all the users in the whole database just with one user token

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#202]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
**ONLY SUPER ADMINS ARE MEANT TO HAVE THIS RIGHT**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@Naza
Please include your slack username here

**Additional context**

**Comment by emasontech** [comment]
I will hand this one.. By access the ID form the token the query the dB with that ID cheers..

**Comment by mhizterkeyz** [comment]
If this issue is still open to claiming, i will like to take it. I will deliver within the first hour of assignment, and yeah I'm doing exactly what the other person above said he was going to do since 15 hours aga
