### ISSUE TITLE
response says name and email not set after login

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#203]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
Name and email should show in the response

**Screenshots**
![image](https://user-images.githubusercontent.com/50022245/86222701-80d5f380-bb7e-11ea-83a6-53770d30e433.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by emasontech** [comment]
I can fix this

**Comment by chinazaaa** [comment]
Have you fixed it now
