### ISSUE TITLE
customer/all is not working

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#206]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
Should return all the user customers.

**Screenshots**
![image](https://user-images.githubusercontent.com/50022245/86223119-0b1e5780-bb7f-11ea-9e02-57d3de898e09.png)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by kenny-67** [comment]
I'll like to take this

**Comment by chinazaaa** [comment]
Have you fixed it

**Comment by mhizterkeyz** [comment]
The solution (pull #217) provided for this issue needs improvement. customer/all should only get all the customers of the current user, not all the customers on the DB. I can improve on this and deliver within the first hour of assignment.
