### ISSUE TITLE
password does not allow special characters

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#207]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by Hack-Light** [comment]
I can handle this

**Comment by emasontech** [comment]
Let me fix this with. RegEx.. 😇 Expert

**Comment by olawalejuwonm** [comment]
I can fix this

**Comment by chinazaaa** [comment]
Have you fixed it
