### ISSUE TITLE
customer/new not working

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#208]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by judgegodwins** [comment]
I'd like to fix it
