### ISSUE TITLE
User/all endpoint not working

### ISSUE THREAD

**Issue by olawalejuwonm** [hngi/sentry-my-customer-api#215]
**What Functionality / Service / Endpoint would you like to add?**
The User/all endpoint is not returning all user as expected.

**Describe this Functionality / Service / Endpoint**
A clear and concise description of what you want to add.
The User/all endpoint was finding user by id which is not right. The user/all endpoint is specifically meant for getting all users as included in the documentation and in the comment about the endpoint.

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature. 
I will enable the user/all endpoint to return users in the database

**Slack username**
@OlawaleJuwonM

**Additional context**
The route worked on was user/all/:userid
![Screenshot (13)](https://user-images.githubusercontent.com/52759812/86301653-49a72700-bbfe-11ea-8b91-7782be778cb0.png)
The user/all is specifically for getting all users as included in this documentation
![Screenshot (14)](https://user-images.githubusercontent.com/52759812/86301721-7c511f80-bbfe-11ea-8c5d-43034a8f438f.png)

**Comment by buka4rill** [comment]
Steps to test, postman screenshot?

**Comment by buka4rill** [comment]
Don't bother. I  have tested it. I used a token to get all the users in the database. That is wrong. If I am using a token to get all users, if that token doesn't belong to a super admin, I shouldn't get all users. I should get just the user whose token was inputed.

**Comment by olawalejuwonm** [comment]
@buka4rill I have solved this by using the token of user inputted to return the user.
This is the approach I used

> Firstly validate the token

> I used the details passed in to req.user 

> Since identifier is unique and is required in the user (store_admin) model

> I used req.user.identifier to find only one single user in the database.

Thank you
I have added more commits to my pull request and I have pulled before making the pull request.
