### ISSUE TITLE
/user/update/:user_id endpoint not working

### ISSUE THREAD

**Issue by Hack-Light** [hngi/sentry-my-customer-api#219]
**Describe the bug**
After successfully updating a user. The field still show 'not set'

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**
![nbnhm](https://user-images.githubusercontent.com/52836079/86333554-f952b800-bc43-11ea-8026-00128babf417.PNG)

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
@Light

**Additional context**

**Comment by EmmanuelSeyi** [comment]
I'll take this pls

**Comment by Hack-Light** [comment]
Already fixed
