### ISSUE TITLE
/login/user saves token to the db

### ISSUE THREAD

**Issue by buka4rill** [hngi/sentry-my-customer-api#221]
**Describe the bug**
On each log in, the token should change. It should return a new token. Also, it should not save token to the db.

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):
1. With Postman: Send to http://localhost:3000/login/user
2. Parameters to test: phone_number and password
3. Ensure to have local db connected
4. Token doesn't change on each log in

**Expected behavior**
Token should change on each log in

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**

**Slack username**

**Additional context**

**Comment by olawalejuwonm** [comment]
I am working on this

**Comment by olawalejuwonm** [comment]
@buka4rill I tried removing the api_token from the collections mongodb by pulling out the api_token from the user (store_admin) schema but the api still persists in the response after log in. this might be possibly static or issue in the DB itself

So now I have implemented changing of api_token immediately the user log in

Kindly check the pull request link and see the screenshot for confirmation
https://github.com/hngi/sentry-my-customer-api/pull/225

**Comment by Megxos** [comment]
Why do you want to remove it? Did you put it there?

**Comment by Megxos** [comment]
@buka4rill  can you please close this issue?

**Comment by olawalejuwonm** [comment]
@Megxos no oo, what's the meaning of all this you've started again abi. Don't worry

**Comment by olawalejuwonm** [comment]
@Megxos why can't you just please be patient and read things before concluding.
Please am begging you, this is the second time you've blocked me without giving helpful feedback. According to the issue raised by @buka4rill . He said the token should not be saved in the database, and I tried solving that.. since it doesn't work I left it.. bro please calm down and understand this... I have been working on this

**Comment by buka4rill** [comment]
I closed this because someone has fixed the login in issue. I'm sorry @olawalejuwonm
