### ISSUE TITLE
Fix /store/update/store_id endpoint to update a store

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#227]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by ajdelgados** [comment]
I'm on it

**Comment by Megxos** [comment]
okay

**Comment by Megxos** [comment]
@hngi-bot add "taken"
