### ISSUE TITLE
Fix and update /assistant/new to add store assistant

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#232]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by olawalejuwonm** [comment]
Working on it

**Comment by buka4rill** [comment]
@olawalejuwonm your last PR wasn't merged. It didn't work. You'd have to forfeit one

**Comment by ashggan** [comment]
can I work on it ?

**Comment by olawalejuwonm** [comment]
@ashggan  am working on it
