### ISSUE TITLE
Complaint routes are not working

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#253]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by buka4rill** [comment]
On this!

**Comment by emasontech** [comment]
fixed 
![complain router](https://user-images.githubusercontent.com/51678953/86453355-8b76c100-bd15-11ea-859c-d7fafbe81e0b.PNG)
