### ISSUE TITLE
Update Store_admin details (Update route)

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#263]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**
I should be able to edit the store admin details

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by ajdelgados** [comment]
What is needed update?

**Comment by chinazaaa** [comment]
completed
