### ISSUE TITLE
Fix /complaint

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#269]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by buka4rill** [comment]
I'm on this already

**Comment by mhizterkeyz** [comment]
I'm on this. @script on slack.
