### ISSUE TITLE
Fix /complaint/new

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#270]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by buka4rill** [comment]
I'm on this

**Comment by buka4rill** [comment]
https://github.com/hngi/sentry-my-customer-api/pull/284

**Comment by buka4rill** [comment]
To test: 
1. Create a business owner : http://localhost:3000/register/user
2. Log in Business Owner: http://localhost:3000/login/user
3. Copy business Owner Id and create compliants: http://localhost:3000/complaint/new/:ownerId
4. Send paramenters : name, email, message
