### ISSUE TITLE
Endpoint to upload/update image

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#329]
**Describe the bug**

endpoint to upload/update image

every user is supposed to have a profile picture, and you need to set a default avatar for users, such that once they upload theirs the default one goes off

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**How do you intend to solve this bug?**
Describe in clear and concise manner how you intend to approach fixing this bug.

**Slack username**
Please include your slack username here

**Additional context**

**Comment by olawalejuwonm** [comment]
working on this

**Comment by olawalejuwonm** [comment]
@chinazaaa this has already been worked on
