### ISSUE TITLE
Codebase refractor: Use persistent method to follow one pattern in all the controllers.

### ISSUE THREAD

**Issue by Alao-Abiodun** [hngi/sentry-my-customer-api#65]
Some codebase in the folders needs some refraction for better performance. e.g following javascript convention style, ES6,
 and destructuring.

**To Reproduce Steps to reproduce the behavior (please point us to the relevant files):**
1. Go to the controller folder, the customer controller 
2. The first function they use async/await method and other function they use promises and then the last function they use async/await again, which is not consistent and some other controllers included.
3. I am going to use async/await for all the function and make all of it consistent so it can be readable and understand by other teammates

**Expected behavior A clear and concise description of what you expected to happen.**
The codebase is supposed to be consistent so any if other teammates can understand it so that he/she will not destroy the codebase by mistake.

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Version 22

**How do you intend to solve this bug? Describe in a clear and concise manner how you intend to approach fixing this bug.**
1. Changing some of the controllers to follow one pattern e.g using async/await in all the functions.

**Slack username** 
@abiodundev10620

**Additional context Add any other context about the problem here.**
No

**Comment by piouson** [comment]
@Alao-Abiodun please provide detailed information for better understanding and proper review.
You can also directly link any code lines or files you are referring to:
![image](https://user-images.githubusercontent.com/17856665/85730689-c5324100-b6f1-11ea-8ac5-06eb1ddb4986.png)

**Comment by nerdyphil** [comment]
Not much of a task but okay. 

Approved by @nerdyphil

**Comment by Naijabas** [comment]
Approved by @Naijabas
