### ISSUE TITLE
Call Notification not working

### ISSUE THREAD

**Issue by chinazaaa** [hngi/sentry-my-customer-api#72]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (please point us to the relevant files):

With postman: /call/{customerId}
Put in a Key-Value pair you want to update
Send the request body
{
    "status": 404,
    "code": 20404,
    "moreInfo": "https://www.twilio.com/docs/errors/20404"
}

**Expected behavior**
Should return a message that a call has been placed.
**Screenshots**
![image](https://user-images.githubusercontent.com/50022245/85738065-aafb6180-b6f7-11ea-8b0d-ccfe719c39b1.png)
Desktop (please complete the following information):

OS: Windows
Browser: Chrome
How do you intend to solve this bug?
Slack username
@Naza
Additional context
None

**Comment by Aptcoder** [comment]
can I work on this

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by chinazaaa** [comment]
approved by @chinazaaa

**Comment by naijauser** [comment]
Assigned to @milz.
