### ISSUE TITLE
All responses of our API don't have the same format

### ISSUE THREAD

**Issue by ajdelgados** [hngi/sentry-my-customer-api#74]
**Describe the bug**
A issue have our API, all responses of our API don't have the same format, for example, some response with a object {"status":"string", "data": array of objects} and other just have a array of object

**How do you intend to solve this bug?**
Centralize all response with util/response_manager.js

**Slack username**
@ajdelgados

**Comment by tboy44wiz** [comment]
Can I ask one Question? How do you expect for instance List of Customers to be in Object rather than Array and How do you expect Fetching of a Single user to be in an Array rather than an Object.??? 

**Please answer me if possible with a screenshot.**

**Comment by naijauser** [comment]
If you standardize the response with this response object,
```
const response = {
        error: data.error,
        code: httpCode,
        data: data.response,
        total: data.total,
        message: data.message,
    };
```
It means that every response will have an error property even if successful? And in a case where an error is returned, it would pass a data property? Would this be the case?

**Comment by nerdyphil** [comment]
Approved by @nerdyphil

**Comment by Daemonicc** [comment]
will can use status to indicate failure or success

**Comment by naijauser** [comment]
I've hardly seen any API that has all possible responses embedded, have you? You can share resources.

**Comment by Daemonicc** [comment]
not all possible responses, but responds should have a pattern e.g if all response have a status field. the person consuming the api can check for errors using just the status field

but in a case where each endpoint have there own style of data as he said, that will not be possible

**Comment by naijauser** [comment]
This is not feasible. Its not a pattern I've seen and I can't justify its use.

**Comment by saucecodee** [comment]
I agree with @Daemonicc ... all responses should have the same properties `message, result, success, error `. Then the consumer can decide if it's successful from the success property which is a boolean
