### ISSUE TITLE
{Feat} - Allow users to customize their  reminder

### ISSUE THREAD

**Issue by Daemonicc** [hngi/sentry-my-customer-api#75]
**What Functionality / Service / Endpoint would you like to add?**
Debt-reminder

**Describe this Functionality / Service / Endpoint**
Debt reminder should be automatically sent to debtor 24 hours before expected pay day if the debt havent been paid,

user should may also be allowed to specify days or frequency of sending debt reminder

Take this scenerio. 
If am a store owner and Mr. A need to pay me by July 30. I should be able to set somedays to remind mr A, so that i do not need to com back to the app to send another debt reminder. but if mr A as already paid, then the reminders will automatically not be sent to him.
also a store owner that doesnt set this up. should have a reminder sent to the debtor 24 hours to debt expiration if debt hasnt been paid

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?

**Describe how to intend to go about adding this feature**
will use either Cron-jobs or Job queing

**Slack username**
@Daemon

**Additional context**

**Comment by chinazaaa** [comment]
Change the title to allow users customize their reminders. Since we already have this service.

**Comment by Daemonicc** [comment]
@chinazaaa i have change the title

**Comment by chinazaaa** [comment]
approved by @chinazaaa

**Comment by Daemonicc** [comment]
I will be working on this @chinazaaa
