### ISSUE TITLE
API Should not return HTML

### ISSUE THREAD

**Issue by Daemonicc** [hngi/sentry-my-customer-api#76]
**What Functionality / Service / Endpoint would you like to add?**
Non registered route

**Describe this Functionality / Service / Endpoint**
None registered routes are currently returning Html pages, non found route should return JSON as we are using it in an API that will be served

**Slack username**
@Daemon

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by Naijabas** [comment]
Approved my @Naijabas

**Comment by naijauser** [comment]
Assigned to @daemon
