### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by Ghvstcode** [hngi/sentry-my-customer-api#82]
**What Functionality / Service / Endpoint would you like to add?**
I would like to write unit tests for the Auth routes of the API

**Describe this Functionality / Service / Endpoint**
I would like to test to ensure that the unit tests are passing correctly! 

**Duplicate prevention**
Have you checked that this issue has not been opened by anyone  else?
Yes, I have

**Slack username**
@xt.

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by chinazaaa** [comment]
Approved by @chinazaaa

**Comment by naijauser** [comment]
Assigned to @xt.
