### ISSUE TITLE
Implement Sign in with facebook

### ISSUE THREAD

**Issue by Hopekodi** [hngi/sentry-my-customer-api#89]
**What Functionality / Service / Endpoint would you like to add?**
Users should be able to sign through their Facebook accounts

**Describe this Functionality / Service / Endpoint**
When users click on the Facebook button the Facebook api gives the user access to log in to their Facebook accounts, then their email address is retrieved in that process. They are authenticated using their email. 

**Duplicate prevention**
No

This is how i intend to go about it. Download the Facebook API, visit developers.facebook.com website and create an app, set the required configurations and implement the API on the project

@chikoo

**Comment by Hopekodi** [comment]
Will love to work on it

**Comment by chinazaaa** [comment]
approved by @chinazaaa

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by naijauser** [comment]
Assigned to @ChiKoo

**Comment by buka4rill** [comment]
Merged
