### ISSUE TITLE
Business card endpoint.

### ISSUE THREAD

**Issue by naijauser** [hngi/sentry-my-customer-api#93]
**What Functionality / Service / Endpoint would you like to add?**
An endpoint [GET] to return information required on a business card.

**Describe this Functionality / Service / Endpoint**
This endpoint `/business-card` would return the following information when a GET request is sent to it. 
-  Name of user
- Phone number
- email
- Store address
This information returned will be used to create a business card on the frontend.

**Duplicate prevention**
Nobody has suggested this feature.

**Describe how you intend to go about adding this feature**
Query the database using the user id, use the user id to query the store for the address, package the result appropriately and return.

**Slack username**
@naijauser 

**Additional context**
None

**Comment by Hack-Light** [comment]
Please can you assign this to me

**Comment by naijauser** [comment]
Approved by @naijauser

**Comment by nerdyphil** [comment]
approved by @nerdyphil

**Comment by nerdyphil** [comment]
> Please can you assign this to me
> @Light

sure

**Comment by buka4rill** [comment]
@mhizterkeyz add the PR link over here with those screen shots please

**Comment by mhizterkeyz** [comment]
[PR link](https://github.com/hngi/sentry-my-customer-api/pull/138)

![proof1](https://user-images.githubusercontent.com/38281402/85925861-2e04ef00-b893-11ea-87b2-06490c43359f.png)

![proof2](https://user-images.githubusercontent.com/38281402/85925869-33fad000-b893-11ea-8100-87d512037e6e.png)

![proof3](https://user-images.githubusercontent.com/38281402/85925871-3b21de00-b893-11ea-8c4d-19d739a1d0b1.png)

**Comment by buka4rill** [comment]
Merged.. @chinazaaa Assign points
